#
# Makefile for the fingerprint drivers.
#

# Each configuration option enables a list of files.

obj-$(CONFIG_FINGERPRINT_GOODIX_FOD)	+= goodix_fod/
obj-$(CONFIG_FINGERPRINT_GOODIX_CAP)	+= goodix_cap/
obj-$(CONFIG_FINGERPRINT_XIAOMI_FP)	+= xiaomi_fp/
obj-$(CONFIG_FINGERPRINT_MI_FP_ULTRA) 	+= mi_fp_ultra/